<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Usuarios\Auth\Adapter'                 => __DIR__ . '/src/Usuarios/Auth/Adapter.php',
    'Usuarios\Controller\ApiController'     => __DIR__ . '/src/Usuarios/Controller/ApiController.php',
    'Usuarios\Controller\AuthController'    => __DIR__ . '/src/Usuarios/Controller/AuthController.php',
    'Usuarios\Controller\IndexController'   => __DIR__ . '/src/Usuarios/Controller/IndexController.php',
    'Usuarios\Entity\Usuario'               => __DIR__ . '/src/Usuarios/Entity/Usuario.php',
    'Usuarios\Form\Login'                   => __DIR__ . '/src/Usuarios/Form/Login.php',
    'Usuarios\Form\LoginFilter'             => __DIR__ . '/src/Usuarios/Form/LoginFilter.php',
    'Usuarios\Form\Usuario'                 => __DIR__ . '/src/Usuarios/Form/Usuario.php',
    'Usuarios\Form\UsuarioFilter'           => __DIR__ . '/src/Usuarios/Form/UsuarioFilter.php',
    'Usuarios\Formatter\Status'             => __DIR__ . '/src/Usuarios/Formatter/Status.php',
    'Usuarios\Module'                       => __DIR__ . '/Module.php',
    'Usuarios\Repository\UsuarioRepository' => __DIR__ . '/src/Usuarios/Repository/UsuarioRepository.php',
    'Usuarios\Service\Usuario'              => __DIR__ . '/src/Usuarios/Service/Usuario.php',
    'Usuarios\View\Helper\UserIdentity'     => __DIR__ . '/src/Usuarios/View/Helper/UserIdentity.php',
);
